#! /bin/sh
case $1 in
        -d) /afs/enea.it/por/user/boffa/miniconda3/bin/zstd -d -3 --long=30 --adapt;;
        '') /afs/enea.it/por/user/boffa/miniconda3/bin/zstd -3 --long=30 -T16 --adapt;;
        *)  echo "Unknown option $1">&2; exit 1;;
esac
