#! /bin/sh
case $1 in
        -d) zstd -d --ultra -22  -M1024MB --long=30 --adapt;;
        '') zstd --ultra -22  -M1024MB --long=30 -T32 --adapt;;
        *)  echo "Unknown option $1">&2; exit 1;;
esac